# Site settings
author: Chris Lincoln
title: SyntaX
header-img: img/home-bg.png
email: chris.lincoln12@gmail.com
copyright_name: Chris Lincoln
description: > # this means to ignore newlines until "baseurl:"
  In Progress
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  clincoln12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
